<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.8.0 on win32)" generated="20200130 13:05:21.116" rpa="false">
<suite id="s1" name="Src &amp; test AirTV">
<suite id="s1-s1" name="Src" source="C:\Users\SlingUserB\PycharmProjects\challenges\test1\Roku\automated-channel-testing-master\src">
<status status="PASS" starttime="20200130 13:05:21.287" endtime="20200130 13:05:21.287"></status>
</suite>
<suite id="s1-s2" name="test AirTV" source="C:\Users\SlingUserB\PycharmProjects\challenges\test1\Roku\automated-channel-testing-master\RobotLibrary\Tests\test_AirTV.robot">
<test id="s1-s2-t1" name="Send key">
<kw name="Back">
<arguments>
<arg>3</arg>
</arguments>
<msg timestamp="20200130 13:05:24.053" level="FAIL">No keyword with name 'Back' found.</msg>
<status status="FAIL" starttime="20200130 13:05:24.053" endtime="20200130 13:05:24.053"></status>
</kw>
<status status="FAIL" starttime="20200130 13:05:24.038" endtime="20200130 13:05:24.053" critical="yes">No keyword with name 'Back' found.</status>
</test>
<test id="s1-s2-t2" name="Send key">
<kw name="Down">
<msg timestamp="20200130 13:05:24.069" level="FAIL">No keyword with name 'Down' found.</msg>
<status status="FAIL" starttime="20200130 13:05:24.069" endtime="20200130 13:05:24.069"></status>
</kw>
<status status="FAIL" starttime="20200130 13:05:24.053" endtime="20200130 13:05:24.069" critical="yes">No keyword with name 'Down' found.</status>
</test>
<test id="s1-s2-t3" name="Channel should be launched">
<kw name="Launch the channel">
<arguments>
<arg>${channel_code}</arg>
</arguments>
<msg timestamp="20200130 13:05:24.100" level="FAIL">No keyword with name 'Launch the channel' found.</msg>
<status status="FAIL" starttime="20200130 13:05:24.100" endtime="20200130 13:05:24.100"></status>
</kw>
<status status="FAIL" starttime="20200130 13:05:24.085" endtime="20200130 13:05:24.100" critical="yes">No keyword with name 'Launch the channel' found.</status>
</test>
<test id="s1-s2-t4" name="Check if details screen showed">
<kw name="Send key">
<arguments>
<arg>select</arg>
<arg>4</arg>
</arguments>
<msg timestamp="20200130 13:05:24.100" level="FAIL">Keyword with same name defined multiple times.</msg>
<status status="FAIL" starttime="20200130 13:05:24.100" endtime="20200130 13:05:24.100"></status>
</kw>
<status status="FAIL" starttime="20200130 13:05:24.100" endtime="20200130 13:05:24.100" critical="yes">Keyword with same name defined multiple times.</status>
</test>
<doc>Basic smoke tests</doc>
<status status="FAIL" starttime="20200130 13:05:21.303" endtime="20200130 13:05:24.100"></status>
</suite>
<status status="FAIL" starttime="20200130 13:05:21.116" endtime="20200130 13:05:24.126"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="4">Critical Tests</stat>
<stat pass="0" fail="4">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="4" id="s1" name="Src &amp; test AirTV">Src &amp; test AirTV</stat>
<stat pass="0" fail="0" id="s1-s1" name="Src">Src &amp; test AirTV.Src</stat>
<stat pass="0" fail="4" id="s1-s2" name="test AirTV">Src &amp; test AirTV.test AirTV</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200130 13:05:21.303" level="ERROR">Error in test case file 'C:\Users\SlingUserB\PycharmProjects\challenges\test1\Roku\automated-channel-testing-master\RobotLibrary\Tests\test_AirTV.robot': Creating keyword 'Send key' failed: Keyword with same name defined multiple times.</msg>
<msg timestamp="20200130 13:05:21.303" level="ERROR">Error in test case file 'C:\Users\SlingUserB\PycharmProjects\challenges\test1\Roku\automated-channel-testing-master\RobotLibrary\Tests\test_AirTV.robot': Creating keyword 'Send key' failed: Keyword with same name defined multiple times.</msg>
<msg timestamp="20200130 13:05:21.303" level="ERROR">Error in test case file 'C:\Users\SlingUserB\PycharmProjects\challenges\test1\Roku\automated-channel-testing-master\RobotLibrary\Tests\test_AirTV.robot': Creating keyword 'Send key' failed: Keyword with same name defined multiple times.</msg>
<msg timestamp="20200130 13:05:23.991" level="ERROR">Error in file 'C:\Users\SlingUserB\PycharmProjects\challenges\test1\Roku\automated-channel-testing-master\RobotLibrary\Tests\test_AirTV.robot': Initializing test library 'RobotLibrary' with arguments [ 192.168.1.22 | 90000 | 8000 |  ] failed: ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /v1/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03718238&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Traceback (most recent call last):
  File "C:\Users\SlingUserB\PycharmProjects\challenges\test1\Roku\automated-channel-testing-master\RobotLibrary\Library\RobotLibrary.py", line 35, in __init__
    self._client = WebDriver(ip, timeout, pressDelay)
  File "C:\Users\SlingUserB\PycharmProjects\challenges\test1\Roku\automated-channel-testing-master\RobotLibrary\Library\webDriver.py", line 25, in __init__
    response = self._post(request_url, data)
  File "C:\Users\SlingUserB\PycharmProjects\challenges\test1\Roku\automated-channel-testing-master\RobotLibrary\Library\webDriver.py", line 95, in _post
    return requests.post(url = request_url, data = json.dumps(data))
  File "C:\Users\SlingUserB\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\SlingUserB\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\SlingUserB\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\SlingUserB\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\SlingUserB\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)</msg>
<msg timestamp="20200130 13:05:24.053" level="WARN">Multiple test cases with name 'Send key' executed in test suite 'Src &amp; test AirTV.test AirTV'.</msg>
</errors>
</robot>
